### ISSUE TITLE
Question on Bias.  

### ISSUE THREAD

**Issue by kabonker** [nickbabcock/rrrocket#12]
How does Bias impact the XYZ coordinates.   I am getting some crazy XYZs like:

     "location": {
                          "bias": 262144,
                          "size": {
                            "limit": 21,
                            "value": 17
                          },
                          "x": -204800,
                          "y": 256000,
                          "z": 1701
thanks

**Comment by nickbabcock** [comment]
That output is from rattletrap right? For rattletrap the x, y, z and are already computed for you, whereas rrrocket displays the raw dx, dy, dz contained in the replay and the x, y, z coordinates must be computed.

The raw formula for calculating x,y,z from dx, dy, dz, and bias is:

```
x = dx - bias
y = dy - bias
z = dz - bias
```

So:

```json
"location": {
  "bias": 4096,
  "dx": 6048,
  "dy": 1632,
  "dz": 4113
},
```

Would translate into

```
x: 1952
y: -2464
z: 17
```

I don't know what seemingly out of bounds coordinates actually means. If using rattletrap, maybe try posting on their issue tracker?

**Comment by HopInMyTrunk** [comment]
Do you know how the x,y,z coordinates could be so high? As I look through the output data, the first couple frames have normal coordinates (in the 100s-1000s). Then deeper in the frames I get the bias is in the hundreds of thousands along with x,y,z. Is it an issue with the program or normal? I've looked at multiple JSON files and all seem to do the same thing

**Comment by kabonker** [comment]
Thanks

John Vaughan
757-256-8216

**Comment by nickbabcock** [comment]
solved: https://github.com/tfausak/rattletrap/issues/136
