### ISSUE TITLE
Unable to parse Score, Goals, Saves etc

### ISSUE THREAD

**Issue by gsteger** [nickbabcock/rrrocket#14]
For most replays I'm able to retrieve the Score, Goals, Saves and all of that for each individual player.

But some replays are missing this when being parsed, the PlayerStats part of the data is left out.

Is this a issue with the replay file?

I've added one of the replays that has this issue as a zip.

[no-stats-12BE54134BB94E8945845DABB0562A84.zip](https://github.com/nickbabcock/rrrocket/files/3491973/no-stats-12BE54134BB94E8945845DABB0562A84.zip)

**Comment by nickbabcock** [comment]
I checked with rrrocket and rattletrap and everything was parsed fine, but the "PlayerStats" property was not included in the replay (I'm unable to say why though, as I have never seen it omitted).

**Comment by gsteger** [comment]
I've collected several of these replays and been looking for a pattern but I can't seem to find one, heres my collection in case it's of interest.

I don't know much about the parsing process, but they seem to work just fine when uploaded to ballchasing.com.

[no-stats-2.zip](https://github.com/nickbabcock/rrrocket/files/3492203/no-stats-2.zip)

[no-stats-1.zip](https://github.com/nickbabcock/rrrocket/files/3492195/no-stats-1.zip)

**Comment by nickbabcock** [comment]
> I don't know much about the parsing process, but they seem to work just fine when uploaded to ballchasing.com.

It's pretty subtle. There isn't anything wrong with the parsing. The PlayerStats property is not present in the replay header, thus it does not appear in the json.

If ballchasing if able to display the player stats without it being in the properties section in header, that means they can reconstruct it by looking at the network data (ie: the network_frames.frames` JSON property). Unfortunately I imagine this could be difficult (I think one would have to track the coordinates of the ball throughout the game and determine if the x, y, z are a certain value, but this is only a hunch, and I'm unsure of the best way to achieve this).

**Comment by gsteger** [comment]
I've had a look around and talked to some people about this. What I was told is that if players leave the match before it's completely over that part of the data might be missing from the header. That's the only explanation I could find.
That would explain the issues, so the replays are not corrupt just not saving the stats in the header for some reason.

**Comment by nickbabcock** [comment]
> That would explain the issues, so the replays are not corrupt just not saving the stats in the header for some reason.

Yeah it's a shame 😞
