### ISSUE TITLE
Parser breaking Rocket League update

### ISSUE THREAD

**Issue by CouchFerret** [nickbabcock/rrrocket#151]
Hey, it looks like there was a parser breaking update for Rocket League. I get this error for pretty much all the recent replays. Can you take a look at it pls? Thanks!

I've used this random replay: https://ballchasing.com/replay/436d667b-116f-44d9-b548-f8079484fc80

> rrrocket.exe -n test1.replay
> An error occurred: Unable to parse replay test1.replay: Error decoding frame: attribute unknown or not implemented: actor id / actor object id / attribute id: 47 / 283 / 24. found attribute TAGame.CarComponent_Dodge_TA:DodgeImpulse (unknown to boxcars) on Archetypes.CarComponents.CarComponent_Dodge in network cache data. This is likely due to a rocket league update or an atypical replay. File a bug report! Context: on frame: 134, last updated actor: (actor stream id / object id / name: 47 / 283 / Archetypes.CarComponents.CarComponent_Dodge, attribute stream id / object id / name: 22 / 271 / TAGame.CarComponent_TA:ReplicatedActive, attribute: Byte(3))

**Comment by nickbabcock** [comment]
Thanks for the report! It should be fixed in the latest version. Let me know if you come across any more edge cases.

**Comment by CouchFerret** [comment]
Thanks for the quick update. Works perfectly!
