### ISSUE TITLE
Unable To Get Ball Location After A Goal Is Scored

### ISSUE THREAD

**Issue by Maverick9320** [nickbabcock/rrrocket#256]
Hi, I am trying to get the balls location data (x, y, z) from a replay using the .json file that rrrocket generates. Using python I can successfully extract the data for the location of the ball, until a goal is scored.

It appears that a new ball is created under a different actor_id every time a goal is scored. I have not been able to find any positional data relating to these new actor_ids and it seems that they don't appear in many frames. I tried to use rattletrap and encountered the same problem so I am at a loss. Any advice you can give would be appreciated. 

actor_ids: 
        - 'Ball_TA_0' (1786 Frames)
        - 'Ball_TA_2' (45 Frames)
        - 'Ball_TA_4' (82 Frames)
        - 'Ball_TA_6' (46 Frames)

Thanks, Maverick.

**Comment by nickbabcock** [comment]
Sorry for the delay in response. Unfortunately the data that is parsed is the data we have to work with. And it's up to an upstream client on how to interpret situations like these.
