### ISSUE TITLE
Error parsing latest replay files from Unranked Play

### ISSUE THREAD

**Issue by Jck123** [nickbabcock/rrrocket#258]
Getting the error below when parsing a replay file that was in Unranked and contained bots today. Did not have this issue before when I was playing with bots in private matches.
I am running on **Ubuntu 22.04.3 LTS**, using the program **rrrocket-0.9.9-x86_64-unknown-linux-musl**.
When parsed without the `-n`, the json successfully parses into the attached .json file
[181D63AC470CE9DAED6BCDAFC950D7CD.json](https://github.com/nickbabcock/rrrocket/files/13254891/181D63AC470CE9DAED6BCDAFC950D7CD.json)

If you would like the .replay file I used to parse, please let me know how I can send it to you. I have 2 files with this issue

```
./rrrocket -c -p -n ./181D63AC470CE9DAED6BCDAFC950D7CD.replay > ./181D63AC470CE9DAED6BCDAFC950D7CD.json
An error occurred: Unable to parse replay ./181D63AC470CE9DAED6BCDAFC950D7CD.replay

Caused by:
    0: Error decoding frame: attribute unknown or not implemented: actor id / actor object id / attribute id: 1 / 112 / 28. found attribute TAGame.GameEvent_TA:bIsBotMatch (unknown to boxcars) on Archetypes.GameEvent.GameEvent_Soccar in network cache data. This is likely due to a rocket league update or an atypical replay. File a bug report! Context: on frame: 0, last updated actor: (actor stream id / object id / name: 1 / 112 / Archetypes.GameEvent.GameEvent_Soccar, attribute stream id / object id / name: 27 / 76 / TAGame.GameEvent_TA:BotSkill, attribute: Int(940201477))
    1: Error decoding frame: attribute unknown or not implemented: actor id / actor object id / attribute id: 1 / 112 / 28. found attribute TAGame.GameEvent_TA:bIsBotMatch (unknown to boxcars) on Archetypes.GameEvent.GameEvent_Soccar in network cache data. This is likely due to a rocket league update or an atypical replay. File a bug report! Context: on frame: 0, last updated actor: (actor stream id / object id / name: 1 / 112 / Archetypes.GameEvent.GameEvent_Soccar, attribute stream id / object id / name: 27 / 76 / TAGame.GameEvent_TA:BotSkill, attribute: Int(940201477))
    2: attribute unknown or not implemented: actor id / actor object id / attribute id: 1 / 112 / 28
```

**Comment by nickbabcock** [comment]
Yeah I would be happy to fix this issue. If you upload the replay files here, I can should be able to issue a quick fix.

**Comment by Jck123** [comment]
I am sending this message via email in hopes the attachments reach you, as github's website will not allow me to upload the .replay filetype. If you do not see any attachments, feel free to contact me at ***@***.*** and I can email them to you directly.
Thank you.

________________________________

**Comment by nickbabcock** [comment]
You can create a zip file with the replay and upload the zip, like this:  [sample.c35cc4cf.zip](https://github.com/nickbabcock/rrrocket/files/13257158/sample.c35cc4cf.zip)

**Comment by Jck123** [comment]
Apologies, I should have thought of that.
Here you go
[replays.zip](https://github.com/nickbabcock/rrrocket/files/13257167/replays.zip)

**Comment by nickbabcock** [comment]
0.9.10 has been released, let me know if you are still encountering errors.

**Comment by Jck123** [comment]
Finally got around to trying it out and it confirmed works on my end. Thanks for the quick fix! :)
