### ISSUE TITLE
Latest replays failing

### ISSUE THREAD

**Issue by zcvaters** [nickbabcock/rrrocket#267]
0: Could not decode replay header properties at offset (5654): Did not expect a property of: StructProperty 
1: Did not expect a property of: StructProperty

* CPPRP was updated https://github.com/Bakkes/CPPRP

[3BD08E214F649DD3A20C14AE0F935158.zip](https://github.com/user-attachments/files/17507630/3BD08E214F649DD3A20C14AE0F935158.zip)

**Comment by zcvaters** [comment]
https://github.com/nickbabcock/boxcars/issues/172

**Comment by nickbabcock** [comment]
Thanks for the report. I released v0.9.13. Give it a try!

**Comment by zcvaters** [comment]
Thanks for getting it out! Working fine!
