### ISSUE TITLE
Unable to parse replays

### ISSUE THREAD

**Issue by DangerIsGo** [nickbabcock/rrrocket#3]
60DFE52E4E6DA4E2B8ACDBA79D6E55E9.replay
`Could not parse replay
Attribute error: Unexpected size for string: 1342177280
Unexpected size for string: 1342177280`

7086546B4E9C97D9279BDE8281CA3E7D.replay
`Could not parse replay
Attribute error: Unexpected size for string: 870515036
Unexpected size for string: 870515036`

72AE1E0740E7C060BAA3BB8A9AEDFD71.replay
`Could not parse replay
Actor id: 10 of object id: 232 (GameInfo_Soccar.GameInfo.GameInfo_Soccar:GameReplicationInfoArchetype) but stream id: 18 (Engine.Actor:Rotation) was not implemented. Possible missing implementations for stream id 18
        object 21 (Engine.Actor) has property 19 (Engine.Actor:Rotation)`

FC4279EE4C20ECEA417655BE8EFD3C78.replay
`Could not parse replay
Actor id: 13 of object id: 292 (GameInfo_Soccar.GameInfo.GameInfo_Soccar:GameReplicationInfoArchetype) but stream id: 4 (Engine.Actor:bNetOwner) was not implemented. Possible missing implementations for stream id 4
        object 21 (Engine.Actor) has property 5 (Engine.Actor:bNetOwner)`

All of these happen when I try to do a network parse.  I have attached them as a zip for further investigation.  Thank you!

[replays.zip](https://github.com/nickbabcock/rrrocket/files/3187987/replays.zip)

**Comment by DangerIsGo** [comment]
Here are some more:
game1.replay
`Could not parse replay
Attribute error: Unexpected size for string: 1994961264
Unexpected size for string: 1994961264`

game2.replay
`Could not parse replay
Time was out of range. Backtracking from frame: 2 to 0, the last actor (7) had a stream id of 53. This may mean that a new update of Rocket League updated this attribute. Decoded into PartyLeader(Some(UniqueId { system_id: 7, remote_id: PsyNet([234, 79, 122, 128, 102, 140, 72, 10, 0, 243, 5, 0, 0, 0, 247, 11, 0, 0, 128, 0, 48, 1, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0]), local_id: 0 }))`

game3.replay
`Could not parse replay
Actor id: 1641 was not found`

7F79F0A7481E3EECC40B61AEC81057E1.replay
`Could not parse replay
Actor id: 6 of object id: 232 (GameInfo_Soccar.GameInfo.GameInfo_Soccar:GameReplicationInfoArchetype) but stream id: 22 (Engine.GameReplicationInfo:TimeLimit) was not implemented. Possible missing implementations for stream id 22`

C23B0F4045BE3E9000DE47BF5238059C.replay
`Could not parse replay
Time was out of range. Backtracking from frame: 1 to 0, the last actor (7) had a stream id of 34. This may mean that a new update of Rocket League updated this attribute. Decoded into Reservation(Reservation { number: 0, unique_id: UniqueId { system_id: 7, remote_id: PsyNet(`

[Replays2.zip](https://github.com/nickbabcock/rrrocket/files/3188000/Replays2.zip)

**Comment by nickbabcock** [comment]
Thank you for the report. Were you the one that contacted me earlier? Were these the ones that rattletrap couldn't parse? Have any parser successfully parsed these replays?

**Comment by DangerIsGo** [comment]
I was said person.  Rattletrap could not parse these either.  These were the only two parsers that I have tried as I run these on macOS.

**Comment by nickbabcock** [comment]
Release v0.2.11 contains these fixes
